### ISSUE TITLE
How to set default values on contentDOM on createCodeMirror()

### ISSUE THREAD

**Issue by aquaductape** [riccardoperra/solid-codemirror#17]
I ran into lighthouse issues where the codemirror textbox needed an aria-label.

I ended up editing contentDOM from editor inside `onMount` callback, fixes the issue
```js
const Editor = () => {
  const {
    editorView,
    ref: setEditorRef,
    createExtension,
  } = createCodeMirror();

  // ...

  onMount(() => {
    requestAnimationFrame(() => {
      const { contentDOM } = editorView();
      contentDOM.setAttribute("aria-label", "code textbox");
    });
  });

  return (
    <div
      ref={(el) => {
        onMount(() => {
          setEditorRef(el);
        });
      }}
    />
  );
};
```

But I'm wondering if theres a way to set attributes on the contentDOM by initially instead of updating it after it's mounted, if solid-codemirror doesn't provide such an API, maybe something like this?
```js
  const {
    editorView,
    ref: setEditorRef,
    createExtension,
  } = createCodeMirror({
    contentDOM: {
      "aria-label": "code textbox"
    }
  });
```

**Comment by riccardoperra** [comment]
Hey, can you send the lighthouse accessibility warning here? 👀

Anyway, I remember I had a similar problem while working on my own projects, and I also added a fix like your 

https://github.com/riccardoperra/codeimage/blob/main/apps/codeimage/src/components/CustomEditor/fix-cm-aria-roles-lighthouse.ts

I also saw that there is an open discussion on CodeMirror6 discuss about an accessibility warning but no official resolution

https://discuss.codemirror.net/t/accessibility-warning-in-chrome-lighthouse-report/3950

I can check this weekend if there is a better solution like a CodeMirror extension to avoid this error without using requestAnimationFrame.

I don’t like a lot the “contentDom” property solution because I consider it an extra behavior that should not be present for a simple primitive that just wraps CodeMirror, but I’ll think about it and I’ll update you asap 😁

**Comment by aquaductape** [comment]
Lighthouse error: "ARIA input fields do not have accessible names"
<img width="782" alt="Screenshot 2023-02-17 at 1 19 45 AM" src="https://user-images.githubusercontent.com/29286430/219604099-70f1e517-d9d5-4604-9da9-09ecb0d798a4.png">

With my workaround, I didn't need to remove `aria-expanded`, passes lighthouse score.
> I don’t like a lot the “contentDom” property solution because I consider it an extra behavior that should not be present for a simple primitive that just wraps CodeMirror

I trust your judgment then, just that either CodeMirror maintainer solves this, or having CodeMirror extension or hook that you said would be great

**Comment by riccardoperra** [comment]
Hey @aquaductape, after an investigation I noticed that you can fix this accessibility issue through the [contentAttributes](https://codemirror.net/docs/ref/#view.EditorView^contentAttributes) facet from CodeMirror

I expect the usage will be something like this:

```tsx
const {
  editorView,
  ref: setEditorRef,
  createExtension,
} = createCodeMirror();

createExtension(EditorView.contentAttributes.of({
  "aria-label": "..."
}))
```

**Comment by aquaductape** [comment]
Sick this works! Now my code is cleaner https://github.com/solidjs-community/html-to-solidjsx/commit/517c39a9b28a75a3eadc25234d0950f27190e73e
